structure(
  list(
    code = c(
      1000L, 1100L, 1101L, 1102L, 1103L, 1104L, 
      1105L, 1106L, 1107L, 1108L, 1109L, 1110L, 1111L, 1200L, 1201L, 
      1202L, 1203L, 1204L, 1205L, 1206L, 1207L, 1208L, 1209L, 1210L, 
      1211L, 1212L, 1213L, 1300L, 1301L, 1302L, 1303L, 1304L, 1305L, 
      1306L, 1307L, 1308L, 1309L, 1310L, 1311L, 1312L, 1313L, 1314L, 
      1315L, 1400L, 1401L, 1402L, 1403L, 1404L, 1405L, 1406L, 1407L, 
      1408L, 1409L, 1410L, 1500L, 1501L, 1502L, 1503L, 1504L, 1505L, 
      1506L, 1507L, 1508L, 1600L, 1601L, 1602L, 1603L, 1604L, 1605L, 
      1606L, 1607L, 1700L, 1701L, 1702L, 1703L, 1704L, 1705L, 1706L, 
      1707L, 1708L, 1709L, 1710L, 1711L, 1712L, 1800L, 1801L, 1802L, 
      1803L, 1804L, 1900L, 1901L, 1902L, 1903L, 1904L, 1905L, 1906L, 
      1907L, 1908L, 1909L, 1910L, 1911L, 1912L, 1913L, 2000L, 2001L, 
      2002L, 2003L, 2100L, 2101L, 2102L, 2103L, 2104L, 2105L, 2200L, 
      2201L, 2202L, 2203L, 2204L, 2205L, 2206L, 2207L, 2208L, 2209L, 
      2210L, 2211L, 2212L, 2213L, 2214L, 2215L, 2216L, 2300L, 2301L, 
      2302L, 2303L, 2304L, 2305L, 2306L, 2307L, 2308L, 2309L, 2310L, 
      2311L, 2312L, 2400L, 2401L, 2402L, 2403L, 2404L, 2405L, 2406L, 
      2500L, 2501L, 2502L, 2503L, 2504L, 2505L, 2506L, 2507L, 2508L, 
      2600L, 2601L, 2602L, 2603L, 2604L, 2605L, 2606L, 2607L, 2608L, 
      2609L, 2610L, 2611L, 2612L, 2613L, 2614L, 2700L, 2701L, 2702L, 
      2703L, 2704L, 2705L, 2706L, 2707L, 2708L, 2709L, 2710L, 2711L, 
      2712L, 2713L, 2714L, 2715L, 2716L, 2717L, 2718L, 2719L, 2720L, 
      2721L, 2722L, 2723L, 2724L, 2725L, 2726L, 2727L, 2728L, 2729L, 
      2730L, 2731L, 2732L, 2733L, 2734L, 2735L, 2736L, 2737L, 2738L, 
      2739L, 2740L, 2741L, 2742L, 2743L, 2744L, 2745L, 2746L, 2747L, 
      2748L, 2800L, 2801L, 2802L, 2803L, 2804L, 2805L, 2806L, 2807L, 
      2808L, 2809L, 2900L, 2901L, 2902L, 2903L, 2904L, 2905L, 2906L, 
      2907L, 2908L, 2909L, 2910L, 2911L, 2912L, 2913L, 2914L, 2915L, 
      2916L, 2917L, 2918L, 2919L, 2920L, 2921L, 2922L, 2923L, 3000L, 
      3001L, 3002L, 3003L, 3004L, 3005L, 3100L, 3101L, 3102L, 3103L, 
      3104L, 3105L, 3106L, 3107L, 3108L, 3109L, 3110L, 3200L, 3201L, 
      3202L, 3203L, 3204L, 3205L, 3206L, 3207L, 3300L, 3301L, 3302L, 
      3303L, 3304L, 3305L, 3306L, 3307L, 3308L, 3309L, 3310L, 3311L, 
      3312L, 3313L, 3314L, 3315L, 3316L, 3317L, 3318L, 3319L, 3320L, 
      3321L, 3322L, 3400L, 3401L, 3402L, 3403L, 3404L, 3500L, 3501L, 
      3502L, 3503L, 3504L, 3505L, 3506L, 3600L, 3601L, 3602L, 3603L, 
      3604L, 3605L, 3606L, 3607L, 3608L, 3609L, 3610L, 3611L, 3612L, 
      3613L, 3614L, 3615L, 3616L), 
    field = c(
      "Multidisciplinary", "General Agricultural and Biological Sciences", 
      "Agricultural and Biological Sciences (miscellaneous)", "Agronomy and Crop Science", 
      "Animal Science and Zoology", "Aquatic Science", "Ecology, Evolution, Behavior and Systematics", 
      "Food Science", "Forestry", "Horticulture", "Insect Science", 
      "Plant Science", "Soil Science", "General Arts and Humanities", 
      "Arts and Humanities (miscellaneous)", "History", "Language and Linguistics", 
      "Archeology (arts and humanities)", "Classics", "Conservation", 
      "History and Philosophy of Science", "Literature and Literary Theory", 
      "Museology", "Music", "Philosophy", "Religious Studies", "Visual Arts and Performing Arts", 
      "General Biochemistry, Genetics and Molecular Biology", "Biochemistry, Genetics and Molecular Biology (miscellaneous)", 
      "Aging", "Biochemistry", "Biophysics", "Biotechnology", "Cancer Research", 
      "Cell Biology", "Clinical Biochemistry", "Developmental Biology", 
      "Endocrinology", "Genetics", "Molecular Biology", "Molecular Medicine", 
      "Physiology", "Structural Biology", "General Business, Management and Accounting", 
      "Business, Management and Accounting (miscellaneous)", "Accounting", 
      "Business and International Management", "Management Information Systems", 
      "Management of Technology and Innovation", "Marketing", "Organizational Behavior and Human Resource Management", 
      "Strategy and Management", "Tourism, Leisure and Hospitality Management", 
      "Industrial Relations", "General Chemical Engineering", "Chemical Engineering (miscellaneous)", 
      "Bioengineering", "Catalysis", "Chemical Health and Safety", 
      "Colloid and Surface Chemistry", "Filtration and Separation", 
      "Fluid Flow and Transfer Processes", "Process Chemistry and Technology", 
      "General Chemistry", "Chemistry (miscellaneous)", "Analytical Chemistry", 
      "Electrochemistry", "Inorganic Chemistry", "Organic Chemistry", 
      "Physical and Theoretical Chemistry", "Spectroscopy", "General Computer Science", 
      "Computer Science (miscellaneous)", "Artificial Intelligence", 
      "Computational Theory and Mathematics", "Computer Graphics and Computer-Aided Design", 
      "Computer Networks and Communications", "Computer Science Applications", 
      "Computer Vision and Pattern Recognition", "Hardware and Architecture", 
      "Human-Computer Interaction", "Information Systems", "Signal Processing", 
      "Software", "General Decision Sciences", "Decision Sciences (miscellaneous)", 
      "Information Systems and Management", "Management Science and Operations Research", 
      "Statistics, Probability and Uncertainty", "General Earth and Planetary Sciences", 
      "Earth and Planetary Sciences (miscellaneous)", "Atmospheric Science", 
      "Computers in Earth Sciences", "Earth-Surface Processes", "Economic Geology", 
      "Geochemistry and Petrology", "Geology", "Geophysics", "Geotechnical Engineering and Engineering Geology", 
      "Oceanography", "Paleontology", "Space and Planetary Science", 
      "Stratigraphy", "General Economics, Econometrics and Finance", 
      "Economics, Econometrics and Finance (miscellaneous)", "Economics and Econometrics", 
      "Finance", "General Energy", "Energy (miscellaneous)", "Energy Engineering and Power Technology", 
      "Fuel Technology", "Nuclear Energy and Engineering", "Renewable Energy, Sustainability and the Environment", 
      "General Engineering", "Engineering (miscellaneous)", "Aerospace Engineering", 
      "Automotive Engineering", "Biomedical Engineering", "Civil and Structural Engineering", 
      "Computational Mechanics", "Control and Systems Engineering", 
      "Electrical and Electronic Engineering", "Industrial and Manufacturing Engineering", 
      "Mechanical Engineering", "Mechanics of Materials", "Ocean Engineering", 
      "Safety, Risk, Reliability and Quality", "Media Technology", 
      "Building and Construction", "Architecture", "General Environmental Science", 
      "Environmental Science (miscellaneous)", "Ecological Modeling", 
      "Ecology", "Environmental Chemistry", "Environmental Engineering", 
      "Global and Planetary Change", "Health, Toxicology and Mutagenesis", 
      "Management, Monitoring, Policy and Law", "Nature and Landscape Conservation", 
      "Pollution", "Waste Management and Disposal", "Water Science and Technology", 
      "General Immunology and Microbiology", "Immunology and Microbiology (miscellaneous)", 
      "Applied Microbiology and Biotechnology", "Immunology", "Microbiology", 
      "Parasitology", "Virology", "General Materials Science", "Materials Science (miscellaneous)", 
      "Biomaterials", "Ceramics and Composites", "Electronic, Optical and Magnetic Materials", 
      "Materials Chemistry", "Metals and Alloys", "Polymers and Plastics", 
      "Surfaces, Coatings and Films", "General Mathematics", "Mathematics (miscellaneous)", 
      "Algebra and Number Theory", "Analysis", "Applied Mathematics", 
      "Computational Mathematics", "Control and Optimization", "Discrete Mathematics and Combinatorics", 
      "Geometry and Topology", "Logic", "Mathematical Physics", "Modeling and Simulation", 
      "Numerical Analysis", "Statistics and Probability", "Theoretical Computer Science", 
      "General Medicine", "Medicine (miscellaneous)", "Anatomy", "Anesthesiology and Pain Medicine", 
      "Biochemistry (medical)", "Cardiology and Cardiovascular Medicine", 
      "Critical Care and Intensive Care Medicine", "Complementary and Alternative Medicine", 
      "Dermatology", "Drug Guides", "Embryology", "Emergency Medicine", 
      "Endocrinology, Diabetes and Metabolism", "Epidemiology", "Family Practice", 
      "Gastroenterology", "Genetics (clinical)", "Geriatrics and Gerontology", 
      "Health Informatics", "Health Policy", "Hematology", "Hepatology", 
      "Histology", "Immunology and Allergy", "Internal Medicine", "Infectious Diseases", 
      "Microbiology (medical)", "Nephrology", "Neurology (clinical)", 
      "Obstetrics and Gynecology", "Oncology", "Ophthalmology", "Orthopedics and Sports Medicine", 
      "Otorhinolaryngology", "Pathology and Forensic Medicine", "Pediatrics, Perinatology and Child Health", 
      "Pharmacology (medical)", "Physiology (medical)", "Psychiatry and Mental Health", 
      "Public Health, Environmental and Occupational Health", "Pulmonary and Respiratory Medicine", 
      "Radiology, Nuclear Medicine and Imaging", "Rehabilitation", 
      "Reproductive Medicine", "Reviews and References (medical)", 
      "Rheumatology", "Surgery", "Transplantation", "Urology", "General Neuroscience", 
      "Neuroscience (miscellaneous)", "Behavioral Neuroscience", "Biological Psychiatry", 
      "Cellular and Molecular Neuroscience", "Cognitive Neuroscience", 
      "Developmental Neuroscience", "Endocrine and Autonomic Systems", 
      "Neurology", "Sensory Systems", "General Nursing", "Nursing (miscellaneous)", 
      "Advanced and Specialized Nursing", "Assessment and Diagnosis", 
      "Care Planning", "Community and Home Care", "Critical Care Nursing", 
      "Emergency Nursing", "Fundamentals and Skills", "Gerontology", 
      "Issues, Ethics and Legal Aspects", "Leadership and Management", 
      "LPN and LVN", "Maternity and Midwifery", "Medical and Surgical Nursing", 
      "Nurse Assisting", "Nutrition and Dietetics", "Oncology (nursing)", 
      "Pathophysiology", "Pediatrics", "Pharmacology (nursing)", "Psychiatric Mental Health", 
      "Research and Theory", "Review and Exam Preparation", "General Pharmacology, Toxicology and Pharmaceutics", 
      "Pharmacology, Toxicology and Pharmaceutics (miscellaneous)", 
      "Drug Discovery", "Pharmaceutical Science", "Pharmacology", "Toxicology", 
      "General Physics and Astronomy", "Physics and Astronomy (miscellaneous)", 
      "Acoustics and Ultrasonics", "Astronomy and Astrophysics", "Condensed Matter Physics", 
      "Instrumentation", "Nuclear and High Energy Physics", "Atomic and Molecular Physics, and Optics", 
      "Radiation", "Statistical and Nonlinear Physics", "Surfaces and Interfaces", 
      "General Psychology", "Psychology (miscellaneous)", "Applied Psychology", 
      "Clinical Psychology", "Developmental and Educational Psychology", 
      "Experimental and Cognitive Psychology", "Neuropsychology and Physiological Psychology", 
      "Social Psychology", "General Social Sciences", "Social Sciences (miscellaneous)", 
      "Archeology", "Development", "Education", "Geography, Planning and Development", 
      "Health (social science)", "Human Factors and Ergonomics", "Law", 
      "Library and Information Sciences", "Linguistics and Language", 
      "Safety Research", "Sociology and Political Science", "Transportation", 
      "Anthropology", "Communication", "Cultural Studies", "Demography", 
      "Gender Studies", "Life-span and Life-course Studies", "Political Science and International Relations", 
      "Public Administration", "Urban Studies", "General Veterinary", 
      "Veterinary (miscellaneous)", "Equine", "Food Animals", "Small Animals", 
      "General Dentistry", "Dentistry (miscellaneous)", "Dental Assisting", 
      "Dental Hygiene", "Oral Surgery", "Orthodontics", "Periodontics", 
      "General Health Professions", "Health Professions (miscellaneous)", 
      "Chiropractics", "Complementary and Manual Therapy", "Emergency Medical Services", 
      "Health Information Management", "Medical Assisting and Transcription", 
      "Medical Laboratory Technology", "Medical Terminology", "Occupational Therapy", 
      "Optometry", "Pharmacy", "Physical Therapy, Sports Therapy and Rehabilitation", 
      "Podiatry", "Radiological and Ultrasound Technology", "Respiratory Care", 
      "Speech and Hearing"),
    subject_area = c(
      "Multidisciplinary", 
      "Life Sciences", "Life Sciences", "Life Sciences", "Life Sciences", 
      "Life Sciences", "Life Sciences", "Life Sciences", "Life Sciences", 
      "Life Sciences", "Life Sciences", "Life Sciences", "Life Sciences", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Life Sciences", "Life Sciences", "Life Sciences", "Life Sciences", 
      "Life Sciences", "Life Sciences", "Life Sciences", "Life Sciences", 
      "Life Sciences", "Life Sciences", "Life Sciences", "Life Sciences", 
      "Life Sciences", "Life Sciences", "Life Sciences", "Life Sciences", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Life Sciences", "Life Sciences", "Life Sciences", "Life Sciences", 
      "Life Sciences", "Life Sciences", "Life Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Life Sciences", "Life Sciences", "Life Sciences", "Life Sciences", 
      "Life Sciences", "Life Sciences", "Life Sciences", "Life Sciences", 
      "Life Sciences", "Life Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Life Sciences", "Life Sciences", 
      "Life Sciences", "Life Sciences", "Life Sciences", "Life Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Physical Sciences", 
      "Physical Sciences", "Physical Sciences", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Social Sciences & Humanities", "Social Sciences & Humanities", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences", "Health Sciences", "Health Sciences", "Health Sciences", 
      "Health Sciences")),
  class = "data.frame", row.names = c(NA, -334L))